server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
    session:
      timeout: 480m
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always
#
#spring:
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    #url: jdbc:mariadb://172.16.211.49:3306/GeekBlog?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&createDatabaseIfNotExist=true
#    #username: root
#    #password: qwer1234!
#    url: jdbc:mariadb://memberfollow-db.cne10fapbpfh.us-east-1.rds.amazonaws.com:3306/db_member_follow
#    username: admin
#    password: qwer1234
#  jpa:
#    hibernate:
#     ddl-auto: create
#  properties:
#    hibernate:
#      format_sql: true
#      show-sql: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://memberfollow-db.cne10fapbpfh.us-east-1.rds.amazonaws.com:3306/db_member_follow
    username: admin
    password: qwer1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org:
      springframework:
        web=DEBUG:

jwt:
  secret:
    key: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
    #    key: XNkZi1hc2RmLWFkZi1hc2RmLWFzZGZhc2QtZmFzZGYtYXNkZi1hc2RmYXNkZmFzZGZhc2RmCg==
  expiration-ms: 3600000