server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
    session:
      timeout: 480m
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://172.16.211.49:3306/GeekBlog?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: qwer1234!

  jpa:

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        show-sql: true

