server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
    session:
      timeout: 480m
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always

spring:
  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #라이터 DB
      jdbc-url: jdbc:mysql://kea-002-member.cluster-cne10fapbpfh.us-east-1.rds.amazonaws.com:3306/kea-002-member
      #jdbc-url: jdbc:mysql://{host_ip}:{host_port}/{DB_name}?createDatabaseIfNotExist=true
      username: admin
      password: geekaws123!

    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #리더 DB
      jdbc-url: jdbc:mysql://kea-002-member.cluster-ro-cne10fapbpfh.us-east-1.rds.amazonaws.com:3306/kea-002-member
      #jdbc-url: jdbc:mysql://{host_ip}:{host_port}/{DB_name}
      username: admin
      password: geekaws123!

    properties:
      hibernate:
        format_sql: true
        show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org:
      springframework:
        web=DEBUG:

jwt:
  secret:
    key: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
    #    key: XNkZi1hc2RmLWFkZi1hc2RmLWFzZGZhc2QtZmFzZGYtYXNkZi1hc2RmYXNkZmFzZGZhc2RmCg==
  expiration-ms: 3600000